#! /usr/bin/env python
Import('env')
myenv=env.Copy()
knetwalk_sources = [
'cell.cpp', 'main.cpp', 'mainwindow.cpp', 'settings.kcfgc', 'highscores.cpp'
]
myenv.KDEprogram( "knetwalk", knetwalk_sources)
myenv.KDEaddpaths_includes( ['./', '#./'])
myenv.KDEaddlibs( ['qt-mt', 'kio', 'kdecore', 'kdegames'])
myenv.KDEinstall('KDEDATA', 'knetwalk', 'knetwalkui.rc')
myenv.KDEinstall('KDEDATA', 'knetwalk', 'eventsrc')
myenv.KDEinstall('KDEXDG', '', 'knetwalk.desktop')
myenv.KDEinstall('KDEKCFG', '', 'knetwalk.kcfg')

soundfiles="""
sounds/click.wav
sounds/connect.wav
sounds/start.wav
sounds/turn.wav
sounds/win.wav
""".split()

myenv.KDEinstall('KDEDATA', 'knetwalk/sounds', soundfiles)
